library("forecast")
library("TSA")
library("lmtest")

series=read.csv('assignment3.csv')
X = series[,1]
Y = series[,2]
Z = series[,3]

# a)
plot(X, type = 'l')
tsdisplay(X) # ACF & PACF decay slowly indicating our time series is integrated

dX = diff(X)

tsdisplay(dX)
# ACF null after lag of 1. PACF decays exponentially.
# dX is MA(1). with theta roughly equal to 0.5
# X is ARIMA(0, 1, 1)

# b)
plot(Y, type = 'l')
tsdisplay(Y)
# ACF seems to decay exponentially. PACF null after lag of 2
# Y is AR(2)

# c)
# Run significance tests on parameter estimates for our models with no drift
modelX = arima(X, order = c(0,1,1), include.mean = FALSE)
coeftest(modelX)
# Pr(>|Z|) = 2.2e-16, so parameter estimate is significant.
coeftest(modelX)[,1] # theta1 estimate of -0.8248

modelY = arima(Y, order = c(2,0,0), include.mean = FALSE)
coeftest(modelY)
# Pr(>|phi1|) = 7.9833e-16 & Pr(>|phi2|) = 1.55e-09, so parameter estimates are significant.
coeftest(modelY)[,1] # phi1 estimate of 0.3471 & phi2 estimate of 0.2602

# d)
plot(Z, type = 'l')
tsdisplay(Z)
# Both ACF & PACF tail off, indicating this is an ARMA process
mean(Z) # Mean roughly equal to 0

dZ = diff(Z)

tsdisplay(dZ)
# ACF/PACF plots seem more credible for initial Z rather than differenced series
# Suggests Z is not an integrated time series

# Indicates we should choose an ARMA model for Z

# e)
modelZ1 = arima(Z, order = c(1, 0, 1), include.mean = FALSE)
coeftest(modelZ1) # coefficients are significant

modelZ2 = arima(Z, order = c(1, 0, 2), include.mean = FALSE)
coeftest(modelZ2) #AR1 & MA1 coefficients are significant, MA2 coefficient is not significant

modelZ3 = arima(Z, order = c(2, 0, 1), include.mean = FALSE)
coeftest(modelZ3) # AR1 & MA1 coefficients are significant, AR2 coefficient is not significant
# We get significant coefficients for AR1 & MA1 terms as the time series is generated by an ARMA(1,1)
# We get non-significant coefficients for the AR2 & MA2 terms as they overfit the model, meaning they are not significantly different from 0

#Q2
# a)
res1 = residuals(modelZ1)
plot(res1)
mean(res1)
var(res1)
qqnorm(res1)
qqline(res1)
shapiro.test(res1)
# p-value of 0.2032, fail to reject normality hypothesis at 5% significance
plot(res1, fitted(modelZ1)) # no obvious pattern in residuals
acf(res1) # acf of residuals null for all lags
Box.test(res1, lag = 12, type = "Ljung-Box", fitdf = 2)
# p-value = 0.3781. Fail to reject hypothesis that residuals distributed as a white noise.
pacf(res1)# pacf of residuals null for all lags

# b)
modelAR2 = arima(Z, order = c(2,0,0), include.mean = FALSE)
resAR2 = residuals(modelAR2)
plot(resAR2)
mean(resAR2)
var(resAR2)
qqnorm(resAR2)
qqline(resAR2)
shapiro.test(resAR2) 
# p-value of 0.6861. Fail to reject normality hypothesis
plot(resAR2, fitted(modelAR2)) # no obvious pattern in residuals
acf(resAR2) # ACF not null for lags less than 5 time steps
Box.test(resAR2, lag = 12, type = "Ljung-Box", fitdf = 2) 
# p-value = 5.285e-11. Reject hypothesis that residuals distributed as a white noise.
pacf(resAR2) # PACF not null for lags 1, 2, 3, 5 & 7


# Q3
# a)
modelZ10 = arima(Z, order = c(10, 0, 0), include.mean = FALSE)
coeftest(modelZ10)
# first 8 paramaeters are significant
# may be due to fact that any ARMA(p, q) model with |phiK| <= 1 for all K can be approximated by an AR(k) model where k is large

res10 = residuals(modelZ10)
plot(res10)
mean(res10)
var(res10)
qqnorm(res10)
qqline(res10)
shapiro.test(res10)
# p-value of 0.2136, fail to reject normality hypothesis at 5% significance
plot(res10, fitted(modelZ10)) # no obvious pattern in residuals
acf(res10) # acf of residuals null for all lags
Box.test(res10, lag = 20, type = "Ljung-Box", fitdf = 10)
# p-value = 0.8274. Fail to reject hypothesis that residuals distributed as a white noise.
pacf(res10) # pacf of residuals null for all lags
